[package]
name = "platform-info"
version = "2.0.0"
authors = ["Alex Lyon <arcterus@mail.com>"]
edition = "2018"
description = "A simple cross-platform interface to get info about a system"

homepage = "https://github.com/uutils/platform-info"
repository = "https://github.com/uutils/platform-info"
readme = "README.md"
keywords = ["platform", "info", "system"]
categories = ["os"]
license = "MIT"

[target.'cfg(not(target_os = "windows"))'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["libloaderapi", "processthreadsapi", "sysinfoapi", "winbase", "winver"] }

[dev-dependencies]
regex = "1"

[features]
default = []
## OS feature shortcodes
windows = [ "feat_os_windows" ]
winos = [ "feat_os_windows" ]
win = [ "feat_os_windows" ]
##
## feature sets
# "feat_os_windows" == build/run on windows platforms
feat_os_windows = []

[[example]]
name = "t"
path = "examples/winos/t.rs"
required-features = [ "feat_os_windows" ]
